version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
